### ISSUE TITLE
New Fantom rounds not appearing in Retool

### ISSUE THREAD

**Issue by meglister** [gitcoinco/grants-stack#2245] opened 2023-08-20 22:43 UTC
**Overview**
The test Fantom rounds that Meg, Andrea, and Fantom team have created are not appearing in Retool.

**Details**
See retool here: https://gitcoin.retool.com/embedded/public/3a51da3b-4c16-4e41-b427-75d06f1f1130?=&chainId=250
Observe recently created rounds not available. Example round id: 0x96e702580d66217c69c3dcbc913aaa6c91955ec0

**Comment by bard** [comment] 2023-08-21 11:42
Same root cause as #2240 so should be fixed by https://github.com/gitcoinco/allo-indexer/issues/247

**Comment by bard** [comment] 2023-08-22 09:43
@meglister this appears to me to be fixed, too

**Comment by michellema1208** [comment] 2023-08-23 18:07
closing this issue as I'm seeing Fantom rounds appearing on Retool!

**Closed by michellema1208** 2023-08-23 18:07 UTC
Labels: chore
