### ISSUE TITLE
Checkout error when contribution amount is close to but under wallet balance

### ISSUE THREAD

**Issue by YukiPL** [gitcoinco/grants-stack#2681] opened 2023-11-24 14:30 UTC
### What was the URL where the error occurred?

https://explorer.gitcoin.co/#/cart

### What happened?

We have a quite a number of tickets saying they are not able to checkout using PGN. Upon checking, it is due to the near gap between the checkout amount and available fund in the wallet. 
For example, checkout amount is $10.20, gas is about $1.20 and available amount in wallet is $11.51. Once it is checkout amount is reduced by $1-2, it works. 
![image](https://github.com/gitcoinco/grants-stack/assets/92294305/9a162ace-bf3d-4c41-870b-029fa44e2f29)
Wallet address for this user is: 0xE2f3f189c7473c1b7b831bF5CFe3D7B70F6c3230

Also see @jesuloluwao 's Loom: https://www.loom.com/share/3c63fa5f82f84b90889773f35edeb3c1

### What should have happened instead?

The transaction should goes through as it is within the available funds in the wallet.

### Steps to Reproduce

1. Go to https://explorer.gitcoin.co/#/cart
2. Try to checkout to amount that is close to what you have in wallet
3. See error.

### What browser(s) are you seeing the problem on?

Chrome

### What chain(s) did the error occur on?

PGN, Optimism confirmed; likely on all chains 

### Relevant log output

```shell
instrument.ts:144 TransactionExecutionError: The total cost (gas * gas fee + value) of executing this transaction exceeds the balance of the account.

This error could arise when the account does not have enough funds to:
 - pay for the total gas fee,
 - pay for the value to send.
 
The cost of the transaction is calculated as `gas * gas fee + value`, where:
 - `gas` is the amount of gas needed for transaction to execute,
 - `gas fee` is the gas fee,
 - `value` is the amount of ether to send to the recipient.
 
Request Arguments:
  chain:  PGN (id: 424)
  from:   0x37e5e6eb36467F98392ebBb35F110FbB8238e6D3
  to:     0x03506eD3f57892C85DB20C36846e9c808aFe9ef4
  value:  0.0098 ETH
  data:   0xaea64c38000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000001a000000000000000000000000000000000000000000000000000000000000001e0000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000022d10c4ecc8000000000000000000000000000b6091aab544ef253c23a37295953aafc9d83668120636c87f66406e917bd61ef99d029bd0dad28d271404543410f247c82d40ffc00000000000000000000000000000000000000000000000000000000000000190000000000000000000000000000000000000000000000000000000000000001000000000000000000000000d4cc0dd193c7dc1d665ae244ce12d7fab337a00800000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000022d10c4ecc8000

Details: [ethjs-rpc] rpc error with payload {"id":4402425969720,"jsonrpc":"2.0","params":["0x02f9029a8201a8588459682f008459682f3c830259b39403506ed3f57892c85db20c36846e9c808afe9ef48722d10c4ecc8000b90224aea64c38000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000001a000000000000000000000000000000000000000000000000000000000000001e0000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000022d10c4ecc8000000000000000000000000000b6091aab544ef253c23a37295953aafc9d83668120636c87f66406e917bd61ef99d029bd0dad28d271404543410f247c82d40ffc00000000000000000000000000000000000000000000000000000000000000190000000000000000000000000000000000000000000000000000000000000001000000000000000000000000d4cc0dd193c7dc1d665ae244ce12d7fab337a00800000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000022d10c4ecc8000c001a0331f2e890553ff1926a2a0b58e6e5af3802d3b31ffc8c35ad392d3a6fab4c6bfa059cbb9aecd627b7c7a204ba7fc5489b8a0fb7a180ff468e471fe5ab1c27052d1"],"method":"eth_sendRawTransaction"} {
  "code": -32603,
  "message": "Internal JSON-RPC error.",
  "data": {
    "code": -32000,
    "message": "insufficient funds for gas * price + value: balance 10081634023050158, tx cost 10198537978463151, overshot 116903955412993"
  },
  "stack": "{\n  \"code\": -32603,\n  \"message\": \"Internal JSON-RPC error.\",\n  \"data\": {\n    \"code\": -32000,\n    \"message\": \"insufficient funds for gas * price + value: balance 10081634023050158, tx cost 10198537978463151, overshot 116903955412993\"\n  },\n  \"stack\": \"Error: Internal JSON-RPC error.\\n    at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:10940)\\n    at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:13880)\\n    at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:14490)\\n    at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:44976)\\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:45978\\n    at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-4.js:12:58139\"\n}\n  at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:10940)\n  at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:13880)\n  at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:14490)\n  at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:44976)\n  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:45978\n  at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-4.js:12:58139"
}
Version: viem@1.10.6
    at $i (getTransactionError.ts:25:10)
    at vs (sendTransaction.ts:185:11)
    at async lu (writeContract.ts:133:16)
    at async w7e (voting.ts:30:10)
    at async checkout (checkoutStore.ts:144:25)
    at async Tt (SummaryContainer.tsx:190:7)
```

### Intercom links
Current case:
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6464550/conversation/67534?view=List

Other cases:
https://app.intercom.com/a/inbox/xaafeyri/inbox/shared/all/conversation/67429?view=List
https://app.intercom.com/a/inbox/xaafeyri/inbox/shared/all/conversation/67490?view=List
https://app.intercom.com/a/inbox/xaafeyri/inbox/shared/all/conversation/67372?view=List

**Comment by bhargavaparoksham** [comment] 2023-11-28 13:06
@YukiPL Unable to replicate this issue. 

![Image](https://github.com/gitcoinco/grants-stack/assets/22616592/57e67207-2558-4340-a0c5-eb332f5a4044)



![Image](https://github.com/gitcoinco/grants-stack/assets/22616592/c7a85120-47c0-431c-bdcf-547a4d8e0c49)


In the above case, I had balance of $5.06 & was able to donate $4.45 & gas fee of $0.55. Total $5.01

Even in the user that was mentioned (0xE2f3f189c7473c1b7b831bF5CFe3D7B70F6c3230), the actual gas fee for their transaction was $1.69 not $1.2 which is why they were not able to donate $10. ref: https://explorer.publicgoods.network/tx/0xe85540c622d94196d63bef9806bc1c425761ee712fbfdff2c95627ab96192dab

cc: @gravityblast @michellema1208

**Comment by YukiPL** [comment] 2023-11-28 14:22
@bhargavaparoksham 
![image](https://github.com/gitcoinco/grants-stack/assets/92294305/ae6dc5cc-1ef1-4768-b402-cfb4ef51d3f6)
![image](https://github.com/gitcoinco/grants-stack/assets/92294305/c87211e0-51c1-4771-9e5a-ceff7b6ca3bc)

**Comment by bhargavaparoksham** [comment] 2023-11-28 14:31
@YukiPL  I'm not able to replicate this. I'm seeing the below error message which is clear mentions what the issue is,

<img width="511" alt="Screenshot 2023-11-28 at 7 58 58 PM" src="https://github.com/gitcoinco/grants-stack/assets/22616592/c4c52e39-8b5a-4fc9-83a0-98279cddc089">

**Comment by michellema1208** [comment] 2023-11-29 15:57
@bhargavaparoksham @gravityblast FYI @jesuloluwao and I were able to replicate this issue (see here: https://discord.com/channels/562828676480237578/1177617631382089829/1179446430499356744) so I'm moving this ticket back into TODO

**Comment by michellema1208** [comment] 2023-11-30 19:21
Closed as issue lies outside of Grants Stack. See: https://discord.com/channels/562828676480237578/1177617631382089829/1179485741424836658

**Closed by michellema1208** 2023-11-30 19:21 UTC
Labels: bug
