### ISSUE TITLE
Average contribution in the round stat (and round results) in manager is incorrect (Citizens round)

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/grants-stack#2004] opened 2023-06-29 08:39 UTC
The correct average for this round (checking the csv) is $1.453

 > Average contribution in the round stat (and round results) in manager is incorrect. Since the beginning, it's around 5, closed out on 5.07

**Link:** [Conversation with kris](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/61721)

**Customer:** [kris](https://app.intercom.com/a/apps/xaafeyri/users/6436a498493bdd1de62e754c/all-conversations)
**Customer ID:** 6dbc5fb9-b0a4-42df-b78d-4ca43f445938
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/61721) when this issue is closed.

**Comment by michellema1208** [comment] 2023-08-16 17:12
Cannot reproduce - closing for now

**Closed by michellema1208** 2023-08-16 17:12 UTC
Labels: bug

**Comment by krrisis** [comment] 2023-09-01 12:30
hey @michellema1208 you asked me to remind you that this is still an issue, you can see the screenshots in the convo linked and see the wrong average in citizens round 1
