### ISSUE TITLE
Donation transaction failing on Optimism

### ISSUE THREAD

**Issue by koday1** [gitcoinco/grants-stack#2253] opened 2023-08-23 00:56 UTC
Kieran - The user has $2 of ETH in their Optimism wallet but the transaction is failing at the third step in Grants Stack. The transaction cost is not higher than $2. Not sure what might be causing this but I attached the user's screenshots here as well.
 
 
 > I have 2 USD, however, when I'm led to the screen to pay the txn it says the cost for the txn is 0 USD

**Link:** [Conversation with cryptomeetlaunamu@gmail.com](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/64622)

**Customer:** [cryptomeetlaunamu@gmail.com](https://app.intercom.com/a/apps/xaafeyri/users/643599f007ea2c8bd33a72e4/all-conversations)
**Customer ID:** 12cc3ed8-6ac9-4373-b8bc-513204f457f7
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/64622) when this issue is closed.
![OPcheckoutissue1](https://github.com/gitcoinco/grants-stack/assets/34075192/b8db6eba-66b7-4a73-be2f-38ba4feb3f5d)
![OPCheckoutissue2](https://github.com/gitcoinco/grants-stack/assets/34075192/11f0d838-585b-44b7-938a-7bdc3e1f29d0)

**Comment by michellema1208** [comment] 2023-09-07 19:22
closing this - was not able to reproduce!

**Closed by michellema1208** 2023-09-07 19:22 UTC
Labels: bug
