### ISSUE TITLE
Explorer: donation amount resetting to 0 after clicking away

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/grants-stack#2001] opened 2023-06-29 08:24 UTC
> This is a TINY bug but wanted to make y'all aware of it. I recorded a Loom video to show you: https://www.loom.com/share/2b53a29818bf4670bffc3f6fc2550cf8?sid=920d7a57-5b89-4dba-82f9-9e6d812a668f

**Link:** [Conversation with Teal Windmill from Valencia](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/61383)

**Customer:** [Teal Windmill from Valencia](https://app.intercom.com/a/apps/xaafeyri/users/6463602392e35b519f598adc/all-conversations)
**Customer ID:** 551b6d54-106f-48f0-a6c0-85060da2726c
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/61383) when this issue is closed.

**Comment by vacekj** [comment] 2023-06-30 10:39
Hey, thanks for reporting this. The checkout page will go through an overhaul for multi-round checkout, which should fix many of these small issues, but keeping this open to verify it has been fixed once multi-round checkout lands.

**Comment by michellema1208** [comment] 2023-08-16 17:16
Note: I was able to reproduce this if you enter a donation amount without clicking out of the box to save the amount, and then scroll down the page.

**Comment by vacekj** [comment] 2023-11-21 20:46
Cannot reproduce, closing

**Closed by vacekj** 2023-11-21 20:46 UTC
Labels: bug, can reproduce
