### ISSUE TITLE
Manager: error during payout

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/grants-stack#2062] opened 2023-07-18 10:57 UTC
<div dir="ltr">Hey all,<div><br></div>
<div>When paying our the Beta Core rounds I noticed some issues. All still exist now and seemed to persist before and after Grants Stack updates.</div>
<div>
<br>All the payouts happened on chain successfully, but what;'s showing in the UI is not accurate. Seems to be a cap of 100 grants that can move to "paid" at a time, and also the unpaid/paid projects seem to change around depending on how you navigate to the tab. See examples in this Loom recording:</div>
<div><span style="color:rgb(33,33,33);font-family:circular,-apple-system,&quot;system-ui&quot;,&quot;Segoe UI&quot;,sans-serif;font-size:14px;white-space:pre"><b>Finalizing Round Payouts 🔄</b> - <a target="_blank" href="https://www.loom.com/share/d5a47d9e24374d54a463e15cd0b981b4" rel="nofollow">Watch Video</a>

<a class="lo-gmail-video-thumb" href="https://www.loom.com/share/d5a47d9e24374d54a463e15cd0b981b4?utm_medium=gif" target="_blank" rel="nofollow"><img src="https://cdn.loom.com/sessions

**Link:** [Conversation with Connor O'Day](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/62549)

**Customer:** [Connor O'Day](https://app.intercom.com/a/apps/xaafeyri/users/6423d9a031ebbc089cb7c9c0/all-conversations)
**Customer ID:** 5f7ea68a-5d2e-4175-8eb1-723cb25ad6fe
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/62549) when this issue is closed.

**Comment by melissa-neira** [comment] 2023-08-04 12:42
I have to wait for my round to start in order to reproduce this - @michellema1208 do you have a round that is ready for payout so we can test?

**Comment by michellema1208** [comment] 2023-08-05 21:02
@melissa-neira this round is ready to be finalized and then paid out (https://rmgitcoin.on.fleek.co/#/round/0x356515cd3e7e996be9e7eac7d025ad54ef5f5a3e) -- however, I only had 2 projects in the round / very low donation amounts as it was used for testing purposes, and I wonder if it won't reproduce the error just due to small scale?

**Comment by melissa-neira** [comment] 2023-08-07 12:12
@michellema1208 I tried to reproduce the bug with the round you sent me but I might've ran into an unrelated bug, lol. here's a loom about it: https://www.loom.com/share/7b65f2ab4d50447eb8f1c19fde8c08db?sid=1112cc3c-2fdc-407d-8564-a9fe2710d17f

the only thing I can think of is that the donations were too low?

**Comment by michellema1208** [comment] 2023-09-27 20:08
closing this issue - have been able to execute payouts smoothly on-platform since Beta rounds!

**Closed by michellema1208** 2023-09-27 20:08 UTC
Labels: bug
