### ISSUE TITLE
bug: contributor stats not showing on project details page

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-stack#1037] opened 2023-01-23 15:29 UTC
**Overview**
The contributor stats (total $ contributed and # of contributors) are not showing up on the project details page (see screenshot). This may be an issue with the API. 

**Screenshots**
https://cloudup.com/cKqGQ3a_GBM

**Comment by DanieleSalatti** [comment] 2023-01-26 01:44
Investigating. Inspecting a grant, this is what I get:

```
{"success":false,"message":"error: summary data not found","data":{}}
```


The call goes to:

https://staging.grants.gitcoin.co/api/v1/data/summary/project/1/0xe575282b376e3c9886779a841a2510f1dd8c2ce4/0xA47669cBc53985333423e4d3D00188f4049fB695

(are we intentionally calling staging? I assume so since `grants.gitcoin.co` does not resolve)

The problem is that `0xA47669cBc53985333423e4d3D00188f4049fB695` is not a project id but the payout address for my grant 🤑


We don't seem to be calling the API to update that value, unless I am missing something. I do see a call to update the round's total (but not the project's) when inspecting the calls.

**Comment by thelostone-mc** [comment] 2023-01-26 14:58
Ah that's likely cause the POST call hasn't fired yet !
This would be

**Comment by hmrtn** [comment] 2023-02-16 01:55
We should implement the rest of the API before starting this, as it will likely affect any changes made about this issue.

**Comment by hmrtn** [comment] 2023-03-27 18:52
Ready to go once https://github.com/gitcoinco/allo-indexer-client/pull/6 is merged

**Closed** 2023-04-03 12:52 UTC
Labels: bug
