### ISSUE TITLE
Newly added round operator can't see round in Manager

### ISSUE THREAD

**Issue by meglister** [gitcoinco/grants-stack#3048] opened 2024-02-26 14:23 UTC
### What was the URL where the error occurred?

manager.gitcoin.co

### What happened?

This user was added as a round operator manually after the round started: 0xEd9f85071353b69eA8d170DAA41d65557AD6F311

When they log in, they can't see the round that they were added to

Round is on Arbitrum and ID is: 0xc45cd4301ee8067a874226f46678ff2c44f12715

### What should have happened instead?

they should see the round they were added to

### Steps to Reproduce

1. Impersonate the user
2. Log into manager

### What chain(s) did the error occur on?

Arbitrum

**Comment by boudra** [comment] 2024-02-26 18:10
- we are confusing the program address with the round address

**0xc45cd4301ee8067a874226f46678ff2c44f12715** is the program address
**0x6142eedc06d80f3b362ce43b4ac52fad679dc850** is the round address

I confirmed address **0xEd9f85071353b69eA8d170DAA41d65557AD6F311** is a round operator and should have access to https://manager.gitcoin.co/#/round/0x6142eedc06d80f3b362ce43b4ac52fad679dc850 (tested with impersonation)

- the address should also be added to the program contract as an operator if we want them to be able to browse to the round detail from the manager homepage, or their list of programs will be empty, this is the program contract: https://arbiscan.io/address/0xc45cd4301ee8067a874226f46678ff2c44f12715

essentially the user has access to the round, but they cannot access it through manager's UI because they have not been added to the program

**Comment by michellema1208** [comment] 2024-02-27 16:39
@boudra is this ready to be closed? If so, can you close it when you see this comment?

**Closed** 2024-02-28 14:04 UTC
Labels: bug
