### ISSUE TITLE
Add QF settings to Round Details tab

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-stack#905] opened 2022-12-22 18:08 UTC
**User Story:**
As a round operator
I want to be able to view and customize my round details after I deploy a round
So that I have more flexibility in running my round

**Acceptance Criteria**
GIVEN that I have a QF round
WHEN I am on that round's Round Details tab
THEN I see the Quadratic Funding settings with my round's details populated

Note: this does not include making information editable

**Product & Design Links:**
[Figma](https://www.figma.com/file/K31Tf7tSn10BuN65VC6YLc/Round-Manager---Hi-Fidelity-Designs?node-id=3373%3A47972&t=MgTuspmLWbZM3U2Y-4)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by michellema1208** [comment] 2023-05-08 17:47
This is outdated/a duplicate of the existing Round Edit Flow milestone!

**Closed by michellema1208** 2023-05-08 17:47 UTC
