### ISSUE TITLE
Add round details tab

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-stack#904] opened 2022-12-22 18:06 UTC
**User Story:**
As a round operator
I want to be able to view and customize my round details after I deploy a round
So that I have more flexibility in running my round

**Acceptance Criteria**
GIVEN that I am on my round dashboard
WHEN I click on the Round Details button in the left nav
THEN I am brought to the Round Details tab

GIVEN that I am on the Round Details tab
WHEN I look at the page
THEN I see the "Changes can be made" text
AND I see the Round & Application Period Settings with my round's information populated

Note: this does not include making the round information editable

**Product & Design Links:**
[Figma](https://www.figma.com/file/K31Tf7tSn10BuN65VC6YLc/Round-Manager---Hi-Fidelity-Designs?node-id=3373%3A47972&t=MgTuspmLWbZM3U2Y-4)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by michellema1208** [comment] 2023-05-08 17:47
This is outdated/a duplicate of the existing Round Edit Flow milestone!

**Closed by michellema1208** 2023-05-08 17:47 UTC
