### ISSUE TITLE
Builder: Applications are not loading 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2366] opened 2023-09-20 14:50 UTC
**Overview**
When I go to an application on Builder, it's no longer loading. This is likely affecting all supported chains. 

<img width="1433" alt="Screen Shot 2023-09-20 at 10 49 53 AM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/84f8518d-c24e-485d-82ae-1f171c52d0e4">

Try: 
- PGN: https://builder.gitcoin.co/#/chains/424/rounds/0x7492a8c4ed29b1f1559888bd832fae5d33e10370 
- Arbitrum: https://builder.gitcoin.co/#/chains/42161/rounds/0x7492a8c4ed29b1f1559888bd832fae5d33e10370

**Steps To Reproduce**

**Observed  behavior**
A clear and concise description of what the observed behavior of the system.

**Expected behavior**
A clear and concise description of what you expected the system to do.

**Screenshots**

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

**Comment by vacekj** [comment] 2023-09-20 15:57
This issue was caused by `builder` expecting a fully-qualified URL, but other apps prefixing `https` and therefore expecting just a bare domain. fixed by overriding the builder env var to be fully qualified in vercel.

**Closed** 2023-09-20 15:58 UTC
Labels: bug
