### ISSUE TITLE
Builder: Projects from Mainnet don't load

### ISSUE THREAD

**Issue by meglister** [gitcoinco/grants-stack#2532] opened 2023-11-01 14:24 UTC
### Updated: 11/2, 8:33AM EST 

**Overview**
When I am using builder, I am not able to load projects from Mainnet. 

**Steps To Reproduce**
1. Go to https://builder.gitcoin.co/#/projects
2. Observe error messages

**Screenshots**

![Image](https://github.com/gitcoinco/grants-stack/assets/26017180/59aa3e40-6288-4d01-bf7f-a62df204bc32)

**Comment by jesuloluwao** [comment] 2023-11-01 15:30
https://app.intercom.com/a/inbox/xaafeyri/inbox/team/6471950/conversation/66458?view=List

**Comment by bard** [comment] 2023-11-02 10:25
This seems to be triggered by the excessive block range for both Optimism and Polygon when using the official RPCs. Trying `Copy as curl` for the Optimism query and replacing the official RPC URL with e.g. the Alchemy URL makes the request succeed; probably the same would happen with Polygon.

Are we using default RPC URLs for Polygon or Optimism or might this be a case of unset variables leading to picking default hardcoded values?

**Comment by bard** [comment] 2023-11-02 12:10
Closing as @gravityblast pushed a tactical fix.

**Comment by michellema1208** [comment] 2023-11-02 12:33
### Archive

**Overview**
When I am using builder, I am not able to load projects from Optimism and Polygon. Projects from Fantom load fine.

**Steps To Reproduce**
1. Go to https://builder.gitcoin.co/#/projects
2. Observe error messages

**Screenshots**
![Screenshot 2023-11-01 at 10 24 43 AM](https://github.com/gitcoinco/grants-stack/assets/72808678/740888d2-896d-4310-a588-facfd8318802)

**Comment by gravityblast** [comment] 2023-11-02 17:00
it's been fixed with https://github.com/gitcoinco/grants-stack/pull/2540

**Closed by gravityblast** 2023-11-02 17:00 UTC
Labels: bug
