### ISSUE TITLE
Explorer: clicking on the "Load more" button in the collection page calls the search service 3 times instead of fetching once

### ISSUE THREAD

**Issue by gravityblast** [gitcoinco/grants-stack#2612] opened 2023-11-15 22:51 UTC
* Open https://explorer.gitcoin.co/#/projects?collectionId=first-time-grantees
* Open network in the dev tools 
* filter by string `applications`
* click "Load more"
* it fetches 2 or 3 times from the search service instead of once

**Comment by carlbarrdahl** [comment] 2023-11-17 13:19
Unable to reproduce, was this fixed in this one?

- https://github.com/gitcoinco/grants-stack/pull/2613

**Comment by michellema1208** [comment] 2024-01-16 20:26
Closing as no longer relevant

**Closed by michellema1208** 2024-01-16 20:26 UTC
