### ISSUE TITLE
Manager: Rendering issue in the manager under 'fund grantees'

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/grants-stack#2244] opened 2023-08-20 22:18 UTC
Just wanted to flag a rendering issue in the manager under 'fund grantees'. When you reduce the size of the screen you get the UI error. It's not responsive enough
![image](https://github.com/gitcoinco/grants-stack/assets/88308638/c3662670-98fb-49aa-8940-ac5985b2d463)

**Link:** [Conversation with kris](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/64282)

**Customer:** [kris](https://app.intercom.com/a/apps/xaafeyri/users/6436a498493bdd1de62e754c/all-conversations)
**Customer ID:** 6dbc5fb9-b0a4-42df-b78d-4ca43f445938
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/64282) when this issue is closed.

**Comment by ArslanYM** [comment] 2023-10-16 07:59
@michellema1208 How do I reach the View Programs page without actually going through the deployment process locally. 

*** 
![lcoals](https://github.com/gitcoinco/grants-stack/assets/104521101/dd3f5710-d162-48c2-8089-499773363b82)



***
To fix the issue #2244, there should be a dummy program present, only then I can fix the UI issue. 

Any suggestions?

**Comment by michellema1208** [comment] 2023-12-15 20:28
Closing this as a duplicate of https://github.com/gitcoinco/grants-stack/issues/2398

**Closed by michellema1208** 2023-12-15 20:28 UTC
Labels: bug, good first issue
