### ISSUE TITLE
Error when adding multiple grants to the basket

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/grants-stack#2006] opened 2023-06-29 09:25 UTC
Hey, so it's impossible to add all grants to my basket at once, not ideal. Next to this and more important, if I select more than a few to add to my basket... the platform unselects them! 

Here's a quick loom video explaining the issue https://www.loom.com/share/069879fd6e064e7ea3850fb478b82376?sid=6b77d4f9-8e83-417a-9210-882e34555eaf

>
**Link:** [Conversation with kris@hotmail.be](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/61650)

**Customer:** [kris@hotmail.be](https://app.intercom.com/a/apps/xaafeyri/users/6436a498493bdd1de62e754c/all-conversations)
**Customer ID:** 6dbc5fb9-b0a4-42df-b78d-4ca43f445938
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/61650) when this issue is closed.

**Comment by michellema1208** [comment] 2023-08-16 17:11
Cannot reproduce - closing for now

**Closed by michellema1208** 2023-08-16 17:11 UTC
Labels: bug, cannot reproduce
