### ISSUE TITLE
Manager: duplicate rows in application CSV download

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#1542] opened 2023-04-20 21:17 UTC
**Overview**
From Boris: there are weird mostly-empty duplicate rows that are included in the csv. not for every project though (see screenshot)

<img width="295" alt="csv" src="https://user-images.githubusercontent.com/26017180/233489636-55c4e3a9-6051-450b-a777-075c68823bb0.png">

This is the application CSV in manager

**Steps To Reproduce**

**Observed  behavior**
A clear and concise description of what the observed behavior of the system.

**Expected behavior**
A clear and concise description of what you expected the system to do.

**Screenshots**

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

**Comment by meg-fsc** [comment] 2023-05-19 16:38
Closing as not able to reproduce -- likely user error

**Closed by meg-fsc** 2023-05-19 16:38 UTC
Labels: bug
