### ISSUE TITLE
View on Etherscan button doesn't persist after finalization. 

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-stack#1765] opened 2023-05-10 00:49 UTC
**Overview**
After finalizing the round, the View on Etherscan button doesn't persist if you refresh the page. The button should be permanently viewable (by all authorized users) after the round has been finalized.

**Comment by michellema1208** [comment] 2023-09-27 20:48
was not able to reproduce with a round I finalized today (https://manager.gitcoin.co/#/round/0xfaf72df9d5384bdb0e56901bf770c27d28af084d) - closing this out!

**Closed by michellema1208** 2023-09-27 20:48 UTC
Labels: bug
