### ISSUE TITLE
Explorer: receiving checkout error even if all remaining projects in cart have values entered 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-stack#2058] opened 2023-07-17 15:02 UTC
**Overview**
**Problem**: if I remove a project from my cart and submit, I'll receive an error "You must enter donations for all projects" even if all the remaining projects have values entered.

GeoWeb Round: https://explorer.gitcoin.co/#/round/10/0x3e92c56dac4a262efcafce7a78381622092754fd

**Steps To Reproduce**

**Observed  behavior**
A clear and concise description of what the observed behavior of the system.

**Expected behavior**
A clear and concise description of what you expected the system to do.

**Screenshots**

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

**Comment by melissa-neira** [comment] 2023-08-04 12:08
Unable to reproduce this issue. Closing this as not planned.

**Closed** 2023-08-04 12:08 UTC
Labels: bug
