### ISSUE TITLE
Builder - Round requirements repeating & spacing issues

### ISSUE THREAD

**Issue by melissa-neira** [gitcoinco/grants-stack#1466] opened 2023-04-13 10:45 UTC
**Overview**
When I was applying to a round I created today, I noticed that the round requirements repeated a bunch. During round creation, I only listed 2 requirements but on the builder side, 16 repeating requirements are showing up. 
**update:** this is also happening on the [Explorer](https://gegitcoin.on.fleek.co/#/round/5/0x95b4632ca485c80e1842a00005397a3940428a7b) side.

Also, there should be more space between the round name and the nav bar - see [Figma](https://www.figma.com/file/obBzCCL8KwoTlVBb5g3ccN/Grant-Hub---Wireframes?node-id=2665-18666&t=kGT40WLnHboNP4t9-4)
![screencapture-staging-grantshub-gitcoin-co-2023-04-13-12_40_49](https://user-images.githubusercontent.com/87520659/231735574-b0726919-1cb0-434b-ad2c-08094e1c5fcb.png)

**Comment by melissa-neira** [comment] 2023-04-13 12:54
@KurtMerbeth I did this on staging! I thought the same, I remember a PR about this from last week

**Comment by thelostone-mc** [comment] 2023-04-13 13:46
Would recommend moving this to the squad backlog

**Comment by thelostone-mc** [comment] 2023-04-15 04:18
Checked it out ! Can't reproduce this.
Closing this out. Do reopen is this still persists

**Closed by thelostone-mc** 2023-04-15 04:18 UTC
Labels: bug
