### ISSUE TITLE
error when trying to download my Vote Coefficients CSV for the Citizens Round

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/grants-stack#2077] opened 2023-07-24 13:54 UTC
It says 'Error: Internal Server Error' when they try to download using the following link

https://indexer-grants-stack.gitcoin.co/api/v1/chains/10/rounds/0x984e29dCB4286c2D9cbAA2c238AfDd8A191Eefbc/exports/vote_coefficients

**Link:** [Conversation with umar](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/62243)

**Customer:** [umar](https://app.intercom.com/a/apps/xaafeyri/users/64ac0017471c413a5277da76/all-conversations)
**Customer ID:** 94e7cfc1-07b0-47fc-87ec-ddb285053cc8
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/62243) when this issue is closed.

**Comment by meglister** [comment] 2023-08-04 20:29
closing, cannot reproduce

**Closed by meglister** 2023-08-04 20:29 UTC
Labels: bug
